[package]
name = "rustana"
version = "0.0.1"
authors = ["telia-oss"]
edition = "2018"
description = """
license = "MIT"

[dependencies]
reqwest = "0.9.16"
serde_json = "1.0.39"
serde = { version = "1.0.91", features = ["derive"] }
