[package]
name = "rustana"
version = "0.1.0"
authors = ["Mohamad al moualem <m.almouallem@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.16"
serde_json = "1.0.39"
serde = { version = "1.0.91", features = ["derive"] }
